### ISSUE TITLE
MsCognitiveServicesApiUrl broken

### ISSUE THREAD

**Issue by Mecanik** [salarcode/AutoResxTranslator#10]
This is not working anymore:

`private const string MsCognitiveServicesApiUrl = "https://api-apc.cognitive.microsofttranslator.com";`

This is the correct link:

`https://api.cognitive.microsofttranslator.com/`

Thanks

**Comment by salarcode** [comment]
I have no way of verifying this, is this the correct url?

**Comment by salarcode** [comment]
maybe here: https://docs.microsoft.com/en-us/azure/cognitive-services/translator/reference/v3-0-translate

**Comment by Mecanik** [comment]
https://docs.microsoft.com/en-us/azure/cognitive-services/translator/reference/v3-0-reference

**Comment by Mecanik** [comment]
<html>
<body>


Geography | Base URL (geographical endpoint)
-- | --
Global (non-regional) | api.cognitive.microsofttranslator.com
United States | api-nam.cognitive.microsofttranslator.com
Europe | api-eur.cognitive.microsofttranslator.com
Asia Pacific | api-apc.cognitive.microsofttranslator.com


</body>
</html>

**Comment by salarcode** [comment]
Thanks updated
