### ISSUE TITLE
there is a new translator (DeepL) with api 

### ISSUE THREAD

**Issue by webspiderteam** [salarcode/AutoResxTranslator#18]
I saw a new translator and it translates better than google. May be you want to add. It has simple api

EXAMPLE REQUEST
curl -X POST 'https://api-free.deepl.com/v2/translate' \
--header 'Authorization: DeepL-Auth-Key [yourAuthKey]' \
--header 'Content-Type: application/json' \
--data '{
  "text": [
    "Hello, world!"
  ],
  "target_lang": "DE"
}'
EXAMPLE RESPONSE
{
  "translations": [
    {
      "detected_source_language": "EN",
      "text": "Hallo, Welt!"
    }
  ]
}

**Comment by salarcode** [comment]
Sorry, this project is maintenance mode, I only accept pull requests

**Comment by webspiderteam** [comment]
I made code and created Pull request #19
