### ISSUE TITLE
Add Italian languagea translating .resx file

### ISSUE THREAD

**Issue by bovirus** [salarcode/AutoResxTranslator#9]
@salarcode 

Is it possible to add Italian language to your project translating your .resx file?

**Comment by salarcode** [comment]
The app UI is not multilingual, so it is only English.
And you can use the app to translate .resx to/from Italian.

**Comment by bovirus** [comment]
@salarcode 

Your program interface now is only in English.
To help users can be useful to have multilangaue UI.
Could you please consider as future plan?
And you can use it also for demonstrate your program.

**Comment by bovirus** [comment]
@salarcode 

Could you please re-consider to add multilanguage option to the GUI?

**Comment by salarcode** [comment]
> @salarcode
> 
> Could you please re-consider to add multilanguage option to the GUI?

Sorry this project is in maintenance mode from me
